const settingDescriptions = {
    name: { zh: "服务器名称", en: "Server name" },
    description: { zh: "服务器描述", en: "Server description" },
    tags: { zh: "服务器标签（逗号分隔）", en: "Server tags (comma separated)" },
    max_players: { zh: "最大玩家数", en: "Maximum number of players" },
    visibility: { zh: "可见性（公开/局域网/隐藏）", en: "Visibility (public/LAN/hidden)" },
    username: { zh: "Factorio 账号用户名", en: "Factorio account username" },
    password: { zh: "Factorio 账号密码", en: "Factorio account password" },
    token: { zh: "Factorio 认证令牌", en: "Factorio authentication token" },
    game_password: { zh: "游戏房间密码", en: "Game password for joining" },
    require_user_verification: { zh: "要求用户验证", en: "Require user verification" },
    max_upload_in_kilobytes_per_second: { zh: "最大上传速度（KB/s）", en: "Max upload speed in KB/s" },
    max_upload_slots: { zh: "最大上传槽位", en: "Maximum upload slots" },
    minimum_latency_in_ticks: { zh: "最小延迟（tick）", en: "Minimum latency in ticks" },
    ignore_player_limit_for_returning_players: { zh: "返回玩家忽略人数限制", en: "Ignore player limit for returning players" },
    allow_commands: { zh: "允许指令", en: "Allow commands" },
    auto_pause: { zh: "自动暂停", en: "Auto pause when no players" },
    only_admins_can_pause_the_game: { zh: "仅管理员可暂停", en: "Only admins can pause" },
    autosave_interval: { zh: "自动保存间隔（分钟）", en: "Auto-save interval (minutes)" },
    autosave_slots: { zh: "自动保存槽位数", en: "Number of auto-save slots" },
    autosave_only_on_server: { zh: "仅在服务器自动保存", en: "Auto-save only on server" },
    non_blocking_saving: { zh: "非阻塞保存", en: "Non-blocking saving" },
    afk_autokick_interval: { zh: "AFK 自动踢出间隔（分钟）", en: "AFK auto-kick interval (minutes)" },
    admins: { zh: "管理员（逗号分隔）", en: "Admins (comma separated)" },
    minimum_segment_size: { zh: "最小区域大小", en: "Minimum segment size" },
    minimum_segment_size_peer_count: { zh: "最小区域对等数量", en: "Minimum segment size peer count" },
    maximum_segment_size: { zh: "最大区域大小", en: "Maximum segment size" },
    maximum_segment_size_peer_count: { zh: "最大区域对等数量", en: "Maximum segment size peer count" },
};

export default settingDescriptions;
