const settingDescriptions = {
    name: { zh: "服务器名称，将在服务器列表中显示", en: "Server name shown in the server browser" },
    description: { zh: "服务器描述，最多 5000 字符", en: "Server description, up to 5000 characters" },
    tags: { zh: "游戏标签列表（逗号分隔）", en: "List of game tags (comma separated)" },
    max_players: { zh: "最大在线玩家数。0 为不限制", en: "Max simultaneous players. 0 = unlimited" },
    visibility: { zh: "服务器可见性：public（公开）/ lan（局域网）/ hidden（隐藏）", en: "Visibility: public / LAN / hidden" },
    username: { zh: "Factorio 账号用户名（公开服务器必填）", en: "Factorio.com username (required for public servers)" },
    password: { zh: "Factorio 密码（建议用 Token 代替）", en: "Factorio.com password (use token instead)" },
    token: { zh: "认证令牌（推荐）。factorio.com/profile 获取", en: "Auth token from factorio.com/profile (recommended)" },
    game_password: { zh: "加入游戏的房间密码，留空则无需密码", en: "Password to join the game. Empty = no password" },
    require_user_verification: { zh: "是否验证玩家 Factorio 账号身份", en: "Verify player identity via Factorio account" },
    max_upload_in_kilobytes_per_second: { zh: "最大上传速度（KB/s），0 为不限制", en: "Max upload speed in KB/s. 0 = unlimited" },
    max_upload_slots: { zh: "最大上传槽位数", en: "Maximum concurrent upload slots" },
    minimum_latency_in_ticks: { zh: "最低延迟（游戏刻），越小响应越快但更吃网络", en: "Minimum latency in ticks. Lower = more responsive" },
    ignore_player_limit_for_returning_players: { zh: "返回玩家是否无视人数上限", en: "Returning players bypass player limit" },
    allow_commands: { zh: "指令权限：true（所有人）/ admins-only / false", en: "Command permission: true (all) / admins-only / false" },
    auto_pause: { zh: "无人在线时自动暂停游戏", en: "Auto-pause when no players connected" },
    only_admins_can_pause_the_game: { zh: "仅允许管理员暂停游戏", en: "Only admins can pause the game" },
    autosave_interval: { zh: "自动保存间隔（分钟）", en: "Auto-save interval in minutes" },
    autosave_slots: { zh: "保留的自动保存槽位数", en: "Number of auto-save slots" },
    autosave_only_on_server: { zh: "仅在服务器端自动保存", en: "Only server performs auto-saves" },
    non_blocking_saving: { zh: "非阻塞保存，保存时游戏不暂停", en: "Non-blocking saving" },
    afk_autokick_interval: { zh: "挂机自动踢出时间（分钟），0 为不禁用", en: "AFK auto-kick in minutes. 0 = never" },
    admins: { zh: "管理员用户名列表（逗号分隔）", en: "Admin usernames (comma separated)" },
    minimum_segment_size: { zh: "最小网络分段大小", en: "Minimum segment size for networking" },
    minimum_segment_size_peer_count: { zh: "最小分段的节点数", en: "Min segment size peer count" },
    maximum_segment_size: { zh: "最大网络分段大小", en: "Maximum segment size for networking" },
    maximum_segment_size_peer_count: { zh: "最大分段的节点数", en: "Max segment size peer count" },
};
export default settingDescriptions;
